---
title: "Azure WIMS Setup"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Azure WIMS Setup}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Accessing the xMart4 databases using your WIMS authentication is a simple process.
This packages builds on the [AzureAuth](https://github.com/Azure/AzureAuth) package,
one developed and maintained by the Azure developers, to ease the access for the user.

### Azure cache directory

Once the xmart4 package is installed, the first thing the user can do is run
`make_azure_rdir()`. This creates a file directory on your machine that will
cache WIMS authentication and limit the need to login to WIMS in your browser
every R session. This mimics the behavior on AzureAuth's `onLoad()` function.

``` r
library(xmart4)
make_azure_rdir()
#> AzureR_dir created at /Users/username/Library/Application Support/AzureR
```

### Azure password

From here, your WIMS account needs to ping the xMart4 Azure servers. To do this,
we need to supply the passwords for the UAT and PROD servers separately. However,
this is not exported with this package because these values are private. You can
contact the maintainer of the package to get these values.

Once received, you need to add them to your `.Renviron` file, which can easily
be edited using the usethis package with `usethis::edit_r_environ()`. Once the
file is opened, just add two lines to the file and save like below (with the
hashes replaced with the actual passwords):

```
XMART_UAT_PASSWORD = "##########"
XMART_PROD_PASSWORD = "##########"
```

Once saved, restart your R session. You can test that this has successfully worked
by running:

``` r
xmart4_token(auth_type = "wims")
```

If this is successful, you can now start exploring any marts that your WHO WIMS
account has access to. Please note you need to work with the specific mart managers
to get your WHO WIMS account access before this setup will work.
